import { DistroInfo, DistroTheme } from '../types';

export const DISTROS: Record<DistroTheme, DistroInfo> = {
  ubuntu: {
    id: 'ubuntu',
    name: 'Ubuntu 24.04 LTS',
    codename: 'Noble Numbat',
    logo: '🟠',
    accentColor: '#E95420',
    badgeBg: 'bg-orange-600/20 text-orange-400 border-orange-500/40',
    kernel: 'Linux 6.8.0-40-generic x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #2c001e 0%, #77216f 50%, #5e2750 100%)',
  },
  arch: {
    id: 'arch',
    name: 'Arch Linux',
    codename: 'Rolling Release',
    logo: '🔵',
    accentColor: '#1793D1',
    badgeBg: 'bg-sky-600/20 text-sky-400 border-sky-500/40',
    kernel: 'Linux 6.10.3-arch1-1 x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #0d1b2a 0%, #1b263b 50%, #0d1b2a 100%)',
  },
  debian: {
    id: 'debian',
    name: 'Debian 12',
    codename: 'Bookworm',
    logo: '🔴',
    accentColor: '#D70A53',
    badgeBg: 'bg-rose-600/20 text-rose-400 border-rose-500/40',
    kernel: 'Linux 6.1.0-23-amd64 x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #161a1d 0%, #301b28 50%, #0f1416 100%)',
  },
  kali: {
    id: 'kali',
    name: 'Kali Linux',
    codename: '2024.3',
    logo: '🐉',
    accentColor: '#2787F5',
    badgeBg: 'bg-blue-600/20 text-blue-400 border-blue-500/40',
    kernel: 'Linux 6.8.11-kali2-amd64 x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #050b14 0%, #0d1f36 50%, #02060d 100%)',
  },
  fedora: {
    id: 'fedora',
    name: 'Fedora Workstation 40',
    codename: 'Rawhide',
    logo: '⚪',
    accentColor: '#294172',
    badgeBg: 'bg-indigo-600/20 text-indigo-400 border-indigo-500/40',
    kernel: 'Linux 6.9.9-200.fc40.x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #0b1a30 0%, #1c3d5a 50%, #0e2038 100%)',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Linux',
    codename: 'Neon Phantom',
    logo: '⚡',
    accentColor: '#FCEE0A',
    badgeBg: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/50',
    kernel: 'Linux 6.9.0-cyberpunk-rt x86_64',
    defaultWallpaper: 'linear-gradient(135deg, #1a0826 0%, #2b0c3d 40%, #051622 100%)',
  },
};

export const DISTRO_ASCII: Record<DistroTheme, string[]> = {
  ubuntu: [
    '        .-.       ',
    '       (.. |      ',
    '       <>  |      ',
    '      / --- \\     ',
    '     ( |   | )    ',
    '   |\\\\_)___(_//|  ',
    '  <__)------(__>  ',
  ],
  arch: [
    '      /\\       ',
    '     /  \\      ',
    '    /\\   \\     ',
    '   /      \\    ',
    '  /   ,,   \\   ',
    ' /   |  |  -\\  ',
    '/_-``\'\'   \'\'-_\\',
  ],
  debian: [
    '   _____    ',
    '  /  __ \\   ',
    ' |  /    |  ',
    ' |  \\___-   ',
    '-_)         ',
    ' \\          ',
    '  `--       ',
  ],
  kali: [
    '  ..............  ',
    '            ..,;: ',
    '        ...,;;;;  ',
    ' .,;  :;::::;:    ',
    '  ;:;;:,,..,      ',
    '   ..,..          ',
    '                  ',
  ],
  fedora: [
    '      /----\\    ',
    '  ___/  / \\ \\   ',
    ' /     /   \\/   ',
    '|   __/ /|      ',
    '|  /___/ |      ',
    ' \\       /      ',
    '  \\_____/       ',
  ],
  cyberpunk: [
    '  ▄█████████▄   ',
    '  █░░░░░░░░░█   ',
    '  █░██░░░██░█   ',
    '  █░░░░░░░░░█   ',
    '  █░░█████░░█   ',
    '  █░░░░░░░░░█   ',
    '  ▀█████████▀   ',
  ],
};
